#!/bin/bash

cp -p glue.auto.tfvars tcp-ecs/aws
cp -p glue.auto.tfvars terraform-aws-sonar-ecs-fargate/sonar
cp -p glue.auto.tfvars terraform-aws-jenkins-stack/jenkins
cp -p glue.auto.tfvars jenkins/environment

find . -name glue.auto.tfvars -ls
