#!/usr/bin/env bash

SERVICE=$1
FLAG1=$2

# Aliases

if [[ $1 == 'db' ]]; then
  docker-compose run --service-ports db
fi

if [[ $1 == 'ui' ]]; then
  SERVICE='ui'
fi
if [[ $1 == 'api' ]]; then
  SERVICE='api'
fi

if [[ $1 == 'core' ]]; then
  docker-compose run --service-ports --use-aliases ui
else
  docker-compose run --service-ports --use-aliases  $FLAG1 $SERVICE
fi
